model_path: C:/okamura/_cnn/epoch30.pt
gpu_enabled: true

img_root: C:/okamura/_cnn/yokoyama_test_images
save_root: test_result

height: 95
width: 95
channels: 3
# class_name: Net

gradcam:
  enabled: true
  layer: conv5
