path:
  # dataset: "D:\\workspace\\repos\\gitlab.com\\ichiya\\prcn2019-datasets\\datasets\\Images-20191014"
  dataset: "D:\\workspace\\pro\\__dataset\\bird_by_yokoyama"
  # dataset: "C:\\ichiya\\prcn2019\\prcn2019-datasets\\datasets\\Images-20191014"

  result_dir: "./results"

dataset:
  limit_size: -1
  valid_size: 0.1
  # ^^^^^^^^ this configs are only valid when `is_pre_splited` is false.

  is_pre_splited: false
  train_dir: ""
  valid_dir: ""
  # ^^^^^^^ this configs are only valid when `is_pre_splited` is true.

  is_shuffle_per_epoch: true
  extensions: ["jpg", "png", "jpeg", "bmp"]

gradcam:
  enabled: false
  # enabled: true
  only_mistaken: false
  layer: "conv5"

network:
  height: 64
  width: 64
  channels: 3

  epoch: 5
  batch: 64
  subdivisions: 32

  save_cycle: 0
  valid_cycle: 1

  gpu_enabled: true
  # is_save_final_model: true
  is_save_final_model: false

  net_name: "LightNet"
  optim_name: "RAdam"

  # class_name: "Net"  # ["Net", "LightNet"] in cnn.py
  # optim_name: "Adam"  # ["Adam", "RAdam"]

option:
  is_show_network_difinition: true
  is_save_log: true
  is_save_mistaken_pred: false
  is_save_config: false
  log_tensorboard: false
  is_save_cm: true  # confusion matrix
