path:
  # dataset: 'D:\workspace\repos\gitlab.com\ichiya\prcn2019-datasets\datasets\Images-20191014'
  # dataset: 'D:\workspace\pro\__dataset\bird_by_yokoyama'
  # dataset: "D:/workspace/repos/github.com/kazuya0202/cnn-with-pytorch/dataset/Images"
  # dataset: "./dataset/Images/"
  dataset: 'C:\ichiya\prcn2019\prcn2019-datasets\datasets\Images-20191014'

  mistaken: "./mistaken"
  model: "./models"
  config: "./config"
  log: "./logs"
  gradcam: "./GradCAM_results"

dataset:
  limit_size: -1
  valid_size: 0.1
  extensions: ["jpg", "png", "jpeg", "bmp"]

  is_shuffle_per_epoch: true

gradcam:
  # enabled: true
  enabled: false
  only_mistaken: true
  layer: "conv5"

  gpu_enabled: false

network:
  height: 60
  width: 60
  channels: 3

  epoch: 10
  batch: 64
  subdivisions: 64

  save_cycle: 0
  valid_cycle: 1

  gpu_enabled: true
  # is_save_final_model: true
  is_save_final_model: false

  class_name: "LightNet"
  # class_name: "Net"  # ["Net", "LightNet", "VGG16"] in cnn.py

option:
  is_show_network_difinition: false
  verbose: true

  # is_debug: true
  is_save_log: false
  is_save_mistaken_pred: false
  is_save_config: false
  log_tensorboard: false
